table xtakso_andmed_clean
	lineageTag: afd527de-32a6-4bfb-90c6-14a55675cb69

	column 'Order ID'
		dataType: int64
		formatString: 0
		lineageTag: a569568a-2c81-41f1-b474-bebde99a2029
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = User

	column 'Order Try ID'
		dataType: int64
		formatString: 0
		lineageTag: ecc80d6a-1646-40bc-9354-1f220228d9f6
		summarizeBy: none
		sourceColumn: Order Try ID

		annotation SummarizationSetBy = User

	column 'Order Created At'
		dataType: dateTime
		formatString: General Date
		lineageTag: 9529b8aa-bd44-49a0-a317-cfc966c86968
		summarizeBy: none
		sourceColumn: Order Created At

		variation Variation
			isDefault
			relationship: 6594c8dc-2cd7-4ec5-89ef-fa4a503e77cb
			defaultHierarchy: LocalDateTable_ed1ff732-bd49-457f-beb8-d1cd305fcf76.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Metered Price'
		dataType: double
		lineageTag: 5bec8f9f-56fd-4833-88a6-a18f2610c6a9
		summarizeBy: none
		sourceColumn: Metered Price

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Upfront Price'
		dataType: double
		lineageTag: 4479c769-fca9-4413-a7c4-ed80a6cb349b
		summarizeBy: none
		sourceColumn: Upfront Price

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Distance of a ride
	column Distance
		dataType: int64
		formatString: 0
		lineageTag: 2e61edfd-f63c-41e4-b0ce-c3a7d61b82bb
		summarizeBy: none
		sourceColumn: Distance

		annotation SummarizationSetBy = User

	/// Duration of a ride
	column Duration
		dataType: int64
		formatString: 0
		lineageTag: 9334baf0-9227-4bf1-8c64-d4717d6d30a3
		summarizeBy: none
		sourceColumn: Duration

		annotation SummarizationSetBy = User

	column 'GPS Confidence'
		dataType: int64
		formatString: 0
		lineageTag: 154a8085-0ef6-4041-bde2-2a78797a7c73
		summarizeBy: none
		sourceColumn: GPS Confidence

		annotation SummarizationSetBy = User

	/// Who entered the address
	column 'Entered By'
		dataType: string
		lineageTag: 9dc1ae2a-d9e9-4b45-8746-5d2c4a7d32d3
		summarizeBy: none
		sourceColumn: Entered By

		annotation SummarizationSetBy = Automatic

	column 'Ride State'
		dataType: string
		lineageTag: e9b6adf3-f074-432f-912c-afb3ae15555b
		summarizeBy: none
		sourceColumn: Ride State

		annotation SummarizationSetBy = Automatic

	column 'Destination Change Number'
		dataType: int64
		formatString: 0
		lineageTag: f3a71bc1-6878-4cd3-9ab6-8eb99e7725fd
		summarizeBy: sum
		sourceColumn: Destination Change Number

		annotation SummarizationSetBy = User

	column 'Prediction Price Type'
		dataType: string
		lineageTag: 5e3e8105-aa4d-4386-8b6e-9088640db951
		summarizeBy: none
		sourceColumn: Prediction Price Type

		annotation SummarizationSetBy = Automatic

	column 'Predicted Distance'
		dataType: double
		lineageTag: 78ca9c97-3164-4deb-ab0e-a760a3c456dd
		summarizeBy: none
		sourceColumn: Predicted Distance

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Predicted Duration'
		dataType: double
		lineageTag: e2183c88-2576-42af-ae99-e2e087eaaa3c
		summarizeBy: none
		sourceColumn: Predicted Duration

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Reason for Pricing Change'
		dataType: string
		lineageTag: 171776d1-50c5-4e27-8e1c-734e42a3f34b
		summarizeBy: none
		sourceColumn: Reason for Pricing Change

		annotation SummarizationSetBy = Automatic

	column 'Ticket ID'
		dataType: int64
		formatString: 0
		lineageTag: e804c57f-42b7-45e5-b456-64aae3260540
		summarizeBy: none
		sourceColumn: Ticket ID

		annotation SummarizationSetBy = User

	column 'Rider App Version'
		dataType: string
		lineageTag: ed4461f4-a3f4-48b3-9c2f-43d2b689f3d7
		summarizeBy: none
		sourceColumn: Rider App Version

		annotation SummarizationSetBy = Automatic

	column 'Order State'
		dataType: string
		lineageTag: 026db876-2da0-4e95-a214-c564e4402bcb
		summarizeBy: none
		sourceColumn: Order State

		annotation SummarizationSetBy = Automatic

	column 'Order Try State'
		dataType: string
		lineageTag: 86c1805c-082a-47ab-93a6-febb89a8b97a
		summarizeBy: none
		sourceColumn: Order Try State

		annotation SummarizationSetBy = Automatic

	column 'Driver App Version'
		dataType: string
		lineageTag: f3e0192b-e8db-49fa-aef7-4c5fb36843ae
		summarizeBy: none
		sourceColumn: Driver App Version

		annotation SummarizationSetBy = Automatic

	column 'Driver Device Unique ID'
		dataType: int64
		formatString: 0
		lineageTag: 9973308b-276a-41a1-9b70-3e8993bb33b6
		summarizeBy: none
		sourceColumn: Driver Device Unique ID

		annotation SummarizationSetBy = User

	column 'Device Name'
		dataType: string
		lineageTag: 675c714a-ae09-4669-b565-60341220fc15
		summarizeBy: none
		sourceColumn: Device Name

		annotation SummarizationSetBy = Automatic

	column 'EU Indicator'
		dataType: int64
		formatString: 0
		lineageTag: f70cf023-10dc-4b65-a57b-f8b0bc31a55b
		summarizeBy: none
		sourceColumn: EU Indicator

		annotation SummarizationSetBy = User

	column 'Overpaid Ride Ticket'
		dataType: int64
		formatString: 0
		lineageTag: a58d663c-4a25-4fb5-bdf5-a9b2c92027c6
		summarizeBy: none
		sourceColumn: Overpaid Ride Ticket

		annotation SummarizationSetBy = User

	column 'Fraud Score'
		dataType: double
		lineageTag: 989a3d00-a18c-46a0-af2b-84887c409469
		summarizeBy: none
		sourceColumn: Fraud Score

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Date
		dataType: string
		lineageTag: f0e19e40-0e0d-42aa-86b3-74f15463c132
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

	column Time
		dataType: string
		lineageTag: d57b6925-f54c-49f4-a620-fb97fdd9d90c
		summarizeBy: none
		sourceColumn: Time

		annotation SummarizationSetBy = Automatic

	column 'Day of Week'
		dataType: string
		lineageTag: 84468f1c-30c6-481b-b08b-433d7e740d1f
		summarizeBy: none
		sourceColumn: Day of Week

		annotation SummarizationSetBy = Automatic

	column 'Day of Week Number'
		dataType: int64
		formatString: 0
		lineageTag: 250a124d-cacc-452a-af48-70426c752711
		summarizeBy: none
		sourceColumn: Day of Week Number

		annotation SummarizationSetBy = User

	column Month
		dataType: int64
		formatString: 0
		lineageTag: a83e93f9-701a-4ad3-930e-f3b89c412084
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = User

	column Year
		dataType: int64
		formatString: 0
		lineageTag: d6bd4a35-7506-41fa-944d-5cdde425effd
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = User

	column 'Is Invalid Ride'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 422a9ec8-02b4-4442-9d77-21d329bb0eeb
		summarizeBy: none
		sourceColumn: Is Invalid Ride

		annotation SummarizationSetBy = Automatic

	column 'Fraud Score Status'
		dataType: string
		lineageTag: ac5a49be-7c1b-4d26-951e-eb4e1821bdb1
		summarizeBy: none
		sourceColumn: Fraud Score Status

		annotation SummarizationSetBy = Automatic

	partition xtakso_andmed_clean = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("localhost:5432", "postgres"),
				    public_takso_andmed_clean = Source{[Schema="public",Item="takso_andmed_clean"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(public_takso_andmed_clean,{{"b_state", "Ride State"}, {"change_reason_pricing", "Reason for Pricing Change"}, {"dest_change_number", "Destination Change Number"}, {"calc_created", "Order Created At"}, {"order_id_new", "Order ID"}, {"order_try_id_new", "Order Try ID"}, {"ticket_id_new", "Ticket ID"}, {"driver_device_uid_new", "Driver Device Unique ID"}, {"date", "Date"}, {"day_of_week", "Day of Week"}, {"day_of_week_nr", "Day of Week Number"}, {"device_name", "Device Name"}, {"distance", "Distance"}, {"driver_app_version", "Driver App Version"}, {"duration", "Duration"}, {"entered_by", "Entered By"}, {"eu_indicator", "EU Indicator"}, {"fraud_score", "Fraud Score"}, {"fraud_score_status", "Fraud Score Status"}, {"gps_confidence", "GPS Confidence"}, {"is_invalid_ride", "Is Invalid Ride"}, {"metered_price", "Metered Price"}, {"month", "Month"}, {"order_state", "Order State"}, {"order_try_state", "Order Try State"}, {"overpaid_ride_ticket", "Overpaid Ride Ticket"}, {"predicted_distance", "Predicted Distance"}, {"predicted_duration", "Predicted Duration"}, {"prediction_price_type", "Prediction Price Type"}, {"rider_app_version", "Rider App Version"}, {"time", "Time"}, {"upfront_price", "Upfront Price"}, {"year", "Year"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

