table Order
	lineageTag: 98bf4c02-8e03-46ab-8cc3-e668986451f6

	column order_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: cc560613-889c-4cd5-898c-d043418e1aec
		summarizeBy: none
		sourceColumn: order_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: int64
		formatString: 0
		lineageTag: f66e7971-3e76-4cfe-8fef-97fceef22d83
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column 'Had Overpaid Ride Ticket'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: b6e39170-eaae-4fe0-8978-3ef672c99580
		summarizeBy: none
		sourceColumn: Had Overpaid Ride Ticket

		annotation SummarizationSetBy = Automatic

	column 'Ride State'
		dataType: string
		lineageTag: 076e9cce-21d9-4560-9094-4b8af86f011a
		summarizeBy: none
		sourceColumn: Ride State

		annotation SummarizationSetBy = Automatic

	column 'Order State'
		dataType: string
		lineageTag: 8357cb95-9ee2-4fd5-829d-a88041a057a0
		summarizeBy: none
		sourceColumn: Order State

		annotation SummarizationSetBy = Automatic

	column 'Order Try ID'
		dataType: int64
		formatString: 0
		lineageTag: 1d788729-29da-4fd9-8068-a51a0b5c5a3f
		summarizeBy: none
		sourceColumn: Order Try ID

		annotation SummarizationSetBy = Automatic

	partition Order = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("localhost", "postgres"),
				    takso_dim_order = Source{[Schema="takso",Item="dim_order"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(takso_dim_order,{{"b_state", "Ride State"}, {"had_overpaid_ride_ticket", "Had Overpaid Ride Ticket"}, {"order_id_new", "Order ID"}, {"order_state", "Order State"}, {"order_try_id_new", "Order Try ID"}})
				in
				    #"Renamed Columns"

	changedProperty = Name

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

