table 'App Version'
	lineageTag: 4c8fe847-bde6-4ba2-8c8e-f5231276538f

	/// App version of rider phone.
	column 'Rider App Version'
		dataType: string
		lineageTag: 51b51984-417d-4a8d-87fd-b1f8aa351870
		summarizeBy: none
		sourceColumn: Rider App Version

		annotation SummarizationSetBy = Automatic

	/// App version of driver phone.
	column 'Driver App Version'
		dataType: string
		lineageTag: 662d45e8-a2e8-4bec-908c-4bb9e2828a6d
		summarizeBy: none
		sourceColumn: Driver App Version

		annotation SummarizationSetBy = Automatic

	/// Key used to link a ride to the App Version dimension.
	column 'App Version Key'
		dataType: int64
		formatString: 0
		lineageTag: 87ef4cf0-6098-4a91-8807-48e4e29238ef
		summarizeBy: none
		sourceColumn: App Version Key

		annotation SummarizationSetBy = Automatic

	column 'Rider App Version Group' =
			
			VAR AppVer = 'App Version'[Rider App Version]
			VAR FirstDot = SEARCH(".", AppVer, 1, 0)
			VAR SecondDot = SEARCH(".", AppVer, FirstDot + 1, 0)
			
			RETURN
			IF(
			    FirstDot > 0 && SecondDot > 0,
			    LEFT(AppVer, SecondDot - 1),
			    AppVer
			)
		lineageTag: cb464966-e900-4d43-bdb5-c24e7263602e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Driver App Version Group' =
			
			VAR AppVer = 'App Version'[Driver App Version]
			VAR FirstDot = SEARCH(".", AppVer, 1, 0)
			VAR SecondDot = SEARCH(".", AppVer, FirstDot + 1, 0)
			
			RETURN
			IF(
			    FirstDot > 0 && SecondDot > 0,
			    LEFT(AppVer, SecondDot - 1),
			    AppVer
			)
		lineageTag: a2ba5d7d-79a8-4871-8a78-674924d17e0a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'App Version' = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("localhost:5432", "postgres"),
				    public_dim_app_version = Source{[Schema="public",Item="dim_app_version"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(public_dim_app_version,{{"app_version_key", "App Version Key"}, {"driver_app_version", "Driver App Version"}, {"rider_app_version", "Rider App Version"}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns",{"App Version Key", "Rider App Version", "Driver App Version", "public.fact_rides"})
				in
				    #"Reordered Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

