table Order
	lineageTag: 7790662d-1a71-4866-ac90-f8eb5080a490

	/// ID of an order.
	column 'Order ID'
		dataType: int64
		formatString: 0
		lineageTag: dc28df3c-3101-45d5-8388-05f09f51400d
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	/// Unique key created to link order-level information across the Rides, Order and Tickets tables.
	column 'Order Key'
		dataType: int64
		formatString: 0
		lineageTag: 8dbe9712-10c9-472f-aedf-1058815b1307
		summarizeBy: none
		sourceColumn: Order Key

		annotation SummarizationSetBy = Automatic

	/// Indicator showing whether an order had at least one customer support ticket related to an overpaid ride.
	column 'Had Overpaid Ride Ticket'
		dataType: int64
		formatString: 0
		lineageTag: ab782d8e-1951-498d-ad1b-8b4c31174d8c
		summarizeBy: none
		sourceColumn: Had Overpaid Ride Ticket

		annotation SummarizationSetBy = Automatic

	/// State of the order.
	column 'Order State'
		dataType: string
		lineageTag: f4d4e6d7-00ae-49d2-852c-ca8422043f25
		summarizeBy: none
		sourceColumn: Order State

		annotation SummarizationSetBy = Automatic

	/// State of the order attempt.
	column 'Order Try State'
		dataType: string
		lineageTag: e012ae29-a6a4-47af-80db-4246b58fcb7e
		summarizeBy: none
		sourceColumn: Order Try State

		annotation SummarizationSetBy = Automatic

	/// ID of the order attempt.
	column 'Order Try ID'
		dataType: int64
		formatString: 0
		lineageTag: 4916aad5-0bd8-440f-bd7b-3e4e3ee2c440
		summarizeBy: none
		sourceColumn: Order Try ID

		annotation SummarizationSetBy = Automatic

	/// Time when the order was created.
	column 'Order Created At'
		dataType: string
		lineageTag: 5f284615-61dd-40f0-b926-0a5a8f052972
		summarizeBy: none
		sourceColumn: Order Created At

		annotation SummarizationSetBy = Automatic

	partition Order = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("localhost:5432", "postgres"),
				    public_dim_order = Source{[Schema="public",Item="dim_order"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(public_dim_order,{{"had_overpaid_ride_ticket", "Had Overpaid Ride Ticket"}, {"order_id_new", "Order ID"}, {"order_key", "Order Key"}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns",{"Order Key", "Order ID", "Had Overpaid Ride Ticket", "public.fact_rides", "public.fact_tickets"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Reordered Columns",{{"order_state", "Order State"}, {"order_try_id_new", "Order Try ID"}, {"order_try_state", "Order Try State"}, {"calc_created", "Order Created At"}}),
				    #"Reordered Columns1" = Table.ReorderColumns(#"Renamed Columns1",{"Order Key", "Order ID", "Had Overpaid Ride Ticket", "Order State", "Order Try State", "Order Try ID", "Order Created At", "public.fact_rides", "public.fact_tickets"})
				in
				    #"Reordered Columns1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

