table Rides
	lineageTag: 7c6d36af-f7a9-435c-b97d-e469a0b8c4dd

	column 'Order ID'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: bc029e9d-1ff0-4f50-8f1d-1df549204e51
		summarizeBy: none
		sourceColumn: Order ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Order Try ID'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: e2d0a0a2-8abb-4e2a-bfaa-26f7f48b0397
		summarizeBy: none
		sourceColumn: Order Try ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Order Created At'
		dataType: string
		isHidden
		lineageTag: 84b7f6ba-233e-41c5-bbaf-e433800cd86f
		summarizeBy: none
		sourceColumn: Order Created At

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// The length of a ride.
	column Time
		dataType: string
		lineageTag: 3cc869cc-6c74-43b3-a3ba-b1b5aa46db10
		summarizeBy: none
		sourceColumn: Time

		annotation SummarizationSetBy = Automatic

	/// Actual price of a ride.
	column 'Metered Price'
		dataType: double
		lineageTag: 070071be-0335-4bca-a0ec-d3b6428a7cf0
		summarizeBy: none
		sourceColumn: Metered Price

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Price promised to the rider based on predicted duration and distance.
	column 'Upfront Price'
		dataType: double
		lineageTag: 6bde1714-f248-4ced-b5a1-87a48992d65b
		summarizeBy: none
		sourceColumn: Upfront Price

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Distance of a ride.
	column Distance
		dataType: int64
		formatString: 0
		lineageTag: a64a69c4-4387-40bc-a6b5-1d2874ff7733
		summarizeBy: none
		sourceColumn: Distance

		annotation SummarizationSetBy = User

	/// Duration of a ride.
	column Duration
		dataType: int64
		formatString: 0
		lineageTag: 092ef7c0-1ca9-4707-b24f-18f8cff51302
		summarizeBy: none
		sourceColumn: Duration

		annotation SummarizationSetBy = User

	/// Number of destination changes by a rider and a driver. It includes the original input of the destination by a rider. That is why the minimum value of it is 1.
	column 'Destination Change Number'
		dataType: int64
		formatString: 0
		lineageTag: 14c76254-2b66-45ab-bef6-11bcd8cbb509
		summarizeBy: sum
		sourceColumn: Destination Change Number

		annotation SummarizationSetBy = User

	/// Predicted distance of a ride based on the pickup and drop off points entered by the rider requesting a car.
	column 'Predicted Distance'
		dataType: double
		lineageTag: f3ae7c62-d407-4513-81e4-e764b3f8520d
		summarizeBy: none
		sourceColumn: Predicted Distance

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Predicted duration of a ride based on the pickup and drop off points entered by the rider requesting a car.
	column 'Predicted Duration'
		dataType: double
		lineageTag: ab8d4aeb-fec1-4be9-abe9-6a6c760356d1
		summarizeBy: none
		sourceColumn: Predicted Duration

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Fraud score of a rider. The higher it is the more likely the rider will cheat.
	column 'Fraud Score'
		dataType: double
		lineageTag: 634d8e89-9d35-426b-9e99-9246b6abd775
		summarizeBy: none
		sourceColumn: Fraud Score

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Indicator for good GPS connection (1 - good one, 0 - bad one).
	column 'GPS Confidence'
		dataType: int64
		formatString: 0
		lineageTag: a3696af8-5395-4f6a-bd1d-7b9bc82d83df
		summarizeBy: none
		sourceColumn: GPS Confidence

		annotation SummarizationSetBy = User

	/// State of a ride (finished implies that the ride was actually done).
	column 'Ride State'
		dataType: string
		lineageTag: ff9cea1d-b3e6-4fa1-8e72-919c6015d292
		summarizeBy: none
		sourceColumn: Ride State

		annotation SummarizationSetBy = Automatic

	column 'Order State'
		dataType: string
		isHidden
		lineageTag: 4258a0c0-ad3b-4fcc-8862-465ee06630f8
		summarizeBy: none
		sourceColumn: Order State

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Order Try State'
		dataType: string
		isHidden
		lineageTag: e147c464-6481-4f46-99d6-9d26cfbf6961
		summarizeBy: none
		sourceColumn: Order Try State

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Whether a ride happens in EU (1 - EU, 0 - non-EU).
	column 'EU Indicator'
		dataType: int64
		formatString: 0
		lineageTag: d6f8accb-e1ba-4374-86bf-6f6cb4bf5318
		summarizeBy: none
		sourceColumn: EU Indicator

		annotation SummarizationSetBy = User

	/// Indicator showing whether the ride is classified as invalid.
	column 'Is Invalid Ride'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: b69ba64f-349e-4da0-9b6c-067a0edef8c9
		summarizeBy: none
		sourceColumn: Is Invalid Ride

		annotation SummarizationSetBy = Automatic

	/// Status associated with the rider fraud score.
	column 'Fraud Score Status'
		dataType: string
		lineageTag: 99ac5455-b166-4974-8d12-9589e6ffc634
		summarizeBy: none
		sourceColumn: Fraud Score Status

		annotation SummarizationSetBy = Automatic

	column 'Date Key'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 6503d21f-6974-461b-8db4-79ca0289a02b
		summarizeBy: none
		sourceColumn: Date Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Unique key identifying a ride in the data model.
	column 'Ride Key'
		dataType: int64
		formatString: 0
		lineageTag: 4a31c4a7-262c-4050-9bfe-21777c44c339
		summarizeBy: none
		sourceColumn: Ride Key

		annotation SummarizationSetBy = User

	column 'Order Key'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 5daa9f51-2b28-43d1-8786-eeafeb9bd79c
		summarizeBy: none
		sourceColumn: Order Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Key used to link a ride to the Device dimension.
	column 'Device Key'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 2b8b4a56-fb2e-49f7-9bf5-518eee2fe4ff
		summarizeBy: none
		sourceColumn: Device Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'App Version Key'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 8dd70a0d-fcee-45d8-a345-f7470a0870cb
		summarizeBy: none
		sourceColumn: App Version Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Pricing Context Key'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: aab6ad54-c4b0-4bf6-8288-d91510acfb3d
		summarizeBy: none
		sourceColumn: Pricing Context Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Percentage difference between actual ride distance and predicted distance.
	column 'Distance Deviation %' =
			
			DIVIDE(
			    'Rides'[Distance] -
			    'Rides'[Predicted Distance],
			    'Rides'[Predicted Distance]
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 82d36081-9056-4631-8cae-2ac5cbaf1c07
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	/// Category grouping rides by the percentage difference between actual and predicted distance.
	column 'Distance Deviation Group' =
			
			SWITCH(
			    TRUE(),
			    'Rides'[Distance Deviation %] < -0.25, "< -25%",
			    'Rides'[Distance Deviation %] < -0.10, "-25% to -10%",
			    'Rides'[Distance Deviation %] <= 0.10, "-10% to +10%",
			    'Rides'[Distance Deviation %] <= 0.25, "+10% to +25%",
			    'Rides'[Distance Deviation %] <= 0.50, "+25% to +50%",
			    "> +50%"
			)
		lineageTag: 84cbca1c-c116-4300-be00-2335401c52b1
		summarizeBy: none
		sortByColumn: 'Distance Deviation Sort'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	/// Numeric helper field used to sort Distance Deviation Group in logical order.
	column 'Distance Deviation Sort' =
			
			SWITCH(
			    TRUE(),
			    'Rides'[Distance Deviation %] < -0.25, 1,
			    'Rides'[Distance Deviation %] < -0.10, 2,
			    'Rides'[Distance Deviation %] <= 0.10, 3,
			    'Rides'[Distance Deviation %] <= 0.25, 4,
			    'Rides'[Distance Deviation %] <= 0.50, 5,
			    6
			)
		formatString: 0
		lineageTag: e3513efe-158a-44e7-9082-ae85edb6a0ed
		summarizeBy: sum

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	/// Percentage difference between metered price and upfront price.
	column 'Price Deviation %' =
			
			DIVIDE(
			    'Rides'[Metered Price] - 'Rides'[Upfront Price],
			    'Rides'[Upfront Price]
			)
		lineageTag: 42ff1a86-06ad-4d5a-8bbf-cd216ea3ef55
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Rides = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("localhost:5432", "postgres"),
				    public_fact_rides = Source{[Schema="public",Item="fact_rides"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(
				    public_fact_rides,
				    {
				        {"b_state", "Ride State"},
				        {"app_version_key", "App Version Key"},
				        {"date_key", "Date Key"},
				        {"device_key", "Device Key"},
				        {"dest_change_number", "Destination Change Number"},
				        {"calc_created", "Order Created At"},
				        {"distance", "Distance"},
				        {"duration", "Duration"},
				        {"eu_indicator", "EU Indicator"},
				        {"fraud_score", "Fraud Score"},
				        {"fraud_score_status", "Fraud Score Status"},
				        {"gps_confidence", "GPS Confidence"},
				        {"is_invalid_ride", "Is Invalid Ride"},
				        {"metered_price", "Metered Price"},
				        {"order_state", "Order State"},
				        {"order_try_id_new", "Order Try ID"},
				        {"order_try_state", "Order Try State"},
				        {"predicted_distance", "Predicted Distance"},
				        {"predicted_duration", "Predicted Duration"},
				        {"ride_key", "Ride Key"},
				        {"time", "Time"},
				        {"upfront_price", "Upfront Price"},
				        {"pricing_context_key", "Pricing Context Key"},
				        {"order_id_new", "Order ID"},
				        {"order_key", "Order Key"}
				    }
				)
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

